services:
  - type: web
    name: ccrs
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /auth/login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
      - key: CCRS_OTP_SEND_EMAIL
        value: "false"
      - key: CCRS_OTP_SEND_SMS
        value: "false"
      - key: CCRS_SMS_PROVIDER
        value: mock
